version: '3'
services:
  app:
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    build: ./docker
    image: amicale-dev
    volumes:
      - ${PWD}:/var/www
    ports: 
      - "80:80"
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: testprojet.localhost
  mysql:
    container_name: ${CONTAINER_MYSQL}
    restart: unless-stopped
    image: mariadb
    env_file:
      - .env
    environment:
      VIRTUAL_HOST: test-mysql.localhost
networks:
  default:
    external:
      name: ${NETWORK}